config/routes.rb
Rails.application.routes.draw do

  resources :reviews

  devise_for :users
  resources :users

  resources :activities

  resources :profile

  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  get 'construction_site' => 'construction_site#index'

  root 'welcome#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base

   has_and_belongs_to_many :users
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit( :job, :services, :description, :images)
    end
end

app/controllers/admin/activities_controller.rb
module Admin
  class ActivitiesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Activity.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Activity.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row ">
    <div class="col-xs-12 col-sm-8 form">
      <div class="field">
        <%= f.label :job %><br>
        <%= f.text_field :job %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-8 form">
      <div class="field">
        <%= f.label :services %><br>
        <%= f.text_field :services %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-8 form">
      <div class="field">
        <%= f.label :description %><br>
        <%= f.text_field :description %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-8 form">
      <div class="field">
        <%= f.label :images %><br>
        <%= f.text_field :images %>
      </div>
    </div>


  </div>
   <div class="actions">
      <%= f.submit %>
    </div>
     <% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row ">
  <div class="col-xs-12 .col-md-8">
    <h1 class="title">Liste d'activitités</h1>
  </div>
</div>
<div class="row ">
       <div class="col-xs-6 col-sm-4 text-center">
          <%= link_to "Nouvelle activité", new_activity_path, :class => "btn btn-default btn-md" %>
       </div>
</div>
<table  class="table table-striped">
  <thead>
    <tr>
      <th>Métier</th>
      <th>Prestations</th>
      <th>Description</th>
      <th>Images</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.job %></td>
        <td><%= activity.services %></td>
        <td><%= activity.description %></td>
        <td><%= activity.images %></td>
        <td><%= link_to 'Visualiser', activity %></td>
        <td><%= link_to 'Éditer', edit_activity_path(activity) %></td>
        <td><%= link_to 'Supprimer', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/activities/new.html.erb
<div class="row ">
  <div class="col-xs-12 .col-md-8">
    <h1 class="title">Nouvelle activité</h1>
  </div>
</div>

<%= render 'form' %>


<div class="row ">
       <div class="col-xs-6 col-sm-4 text-center">
          <%= link_to "Retour", activities_path, :class => "btn btn-default btn-md" %>
       </div>
</div>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Metier:</strong>
  <%= @activity.job %>
</p>

<p>
  <strong>Prestations:</strong>
  <%= @activity.services %>
</p>

<p>
  <strong>Description:</strong>
  <%= @activity.description %>
</p>

<p>
  <strong>Images:</strong>
  <%= @activity.images %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>