config/routes.rb
Rails.application.routes.draw do

  resources :reviews

  devise_for :users
  resources :users

  resources :activities

  resources :profile

  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  get 'construction_site' => 'construction_site#index'

  root 'welcome#index'

end

app/controllers/admin/reviews_controller.rb
module Admin
  class ReviewsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Review.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Review.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    if user_signed_in?
      @reviews = current_user.reviews
    else
      @reviews = Review.all
    end
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user = current_user

    respond_to do |format|
      if @review.save
        format.html { redirect_to reviews_path, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  MAX_MARK = 5
  def average_rating(reviews)
    reviews.map{|r| r.rating}.inject(:+) / reviews.size
  end


  def empty_stars(reviews)
    MAX_MARK - average_rating(reviews)
  end
end

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>



<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row ">
  <div class="col-xs-12 .col-md-8">
    <h1 class="title">Avis & notes</h1>
  </div>
</div>
 <% if @reviews.size > 0 %>
<div class="row ">
  <div class="col-xs-6 col-sm-4 text-center review">
            <p class="note workernote"> <%= average_rating(@reviews) %></p><p class="note notetotal">/5</p>
         <% average_rating(@reviews).times do %>
           <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
         <% end %>
         <% empty_stars(@reviews).times do %>
           <span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>
         <% end %>
   </div>
   <div class="col-xs-6 col-sm-4 text-center">
     <%= link_to "Donnez votre avis", new_review_path, :class => "btn btn-default btn-md" %>
   </div>
</div>
<div class="row ">
  <div class="col-xs-12 col-md-8">
<table class="table tablecomment">
  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td>
         <div class="note comment"> <%= review.rating %> <p class="note notetotal">/5</p></div>
         <% review.rating.times do %>
           <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
         <% end %>
         <% review.empty_stars.times do %>
           <span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>
         <% end %>
          </br>
          <div class="comment" > <%= review.comment %> </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>
</div>
<% else %>
    <div class="row ">
       <div class="col-xs-6 col-sm-4 text-center">
         <%= link_to "Déposez un avis", new_review_path, :class => "btn btn-default btn-md" %>
       </div>
    </div>
<% end %>

app/views/reviews/new.html.erb
<h1>Donnez votre avis</h1>

<div class="row ">
  <div class="col-xs-12 .col-md-8  form">
     <%= link_to "Retour", reviews_path, :class => "btn btn-default btn-md" %>
  </div>
</div>

<%= render 'form' %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>