config/routes.rb
Rails.application.routes.draw do

  resources :reviews

  devise_for :users
  resources :users

  resources :activities

  resources :profile

  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  get 'construction_site' => 'construction_site#index'

  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workspace</title>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!--<a class="navbar-brand" href="#">KiC</a>-->
          <%= link_to "KiC", root_url, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">

            <!-- MENU DEROULANT ARTISAN -->
            <% if user_signed_in? %>
            <li role="separator" class="divider"></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Artisan <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to 'Mon profil',  user_url(current_user) %>
                </li>
                <li>
                  <%= link_to 'Mes activités', activities_url%>
                </li>
                <li>
                  <%= link_to 'Mes avis',  reviews_url %>
                </li>

              </ul>
            </li>
            <% end %>
            <!-- FIN MENU DEROULANT ARTISAN -->

            <!-- MENU DEROULANT CLIENT -->
            <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Client <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li>
                   <%= link_to 'Mon profil',  user_url(current_user) %>
                </li>
                <li>
                  <%= link_to 'Mes avis',  reviews_url %>
                </li>
              </ul>
            </li>
            <% end %>
            <!-- FIN MENU DEROULANT CLIENT -->

            <!-- MENUS LOGIN -->
            <% if user_signed_in? %>
            <li>
                  <%= link_to 'Déconnexion', destroy_user_session_path, method: :delete %>
            </li>
            <% else %>
            <li>
                  <%= link_to 'Connexion', new_user_session_url %>
            </li>
            <li>
                  <%= link_to 'Inscription', new_user_registration_url %>
            </li>
            <% end %>
            <!-- FIN MENUS LOGIN -->

            <!-- MENUS ADMINISTRATION -->
            <li><%= link_to 'Admin', admin_root_url %></li>
            <!-- FIN MENUS ADMINISTRATION -->
          </ul>
        </div>
      </div>
    </nav>

    <%= yield %>

  </body>
</html>